### PR TITLE
DRY refactoring

### PR DESCRIPTION
**Pull request by HCasler**
No a full refactor, or even close. Just picked off some of the easier things

### CODE REVIEW

**Comment by HCasler** [comment]
@rlcee @kutschke  Unless you object, I am going to merge this. It looks like Offline and Production don't have any open PR's so I can check that everything works without interfering with anybody.

I don't anticipate any changes in functionality from this PR, it's just code reorganization.

**Comment by kutschke** [comment]
> @rlcee @kutschke Unless you object, I am going to merge this. It looks like Offline and Production don't have any open PR's so I can check that everything works without interfering with anybody.
> 
> I don't anticipate any changes in functionality from this PR, it's just code reorganization.

OK by me.

**Review by kutschke — APPROVED** [review]
Give Ray a chance to reply but it's OK with me.

**Comment by rlcee** [comment]
Looks fine to me, please proceed

**Pull request merged**
