### PR TITLE
quieter log files; clean workspace in codetools; report which tests started (as well as their return code)

### PR DESCRIPTION
**Pull request by ryuwd**

### CODE REVIEW

**Comment by rlcee** [comment]
What will the additional lines like this
cmsbot_report_test_status "mu2e/${FCL}" "${TEST_STAT_GS}" "${TEST_MSG_GS}" "${TEST_URL_GS}"
do?  What is it reporting to?

**Comment by ryuwd** [comment]
> What will the additional lines like this
> cmsbot_report_test_status "mu2e/${FCL}" "${TEST_STAT_GS}" "${TEST_MSG_GS}" "${TEST_URL_GS}"
> do? What is it reporting to?

It calls a script in Mu2e/CI - see Mu2e/CI#36 - which updates the status of the individual test quietly without spamming the Jenkins logs with the `comment_gh_pr` / `process_pr` logging. I also add a status when the test is started so it is easy to see which tests don't finish / time out.

**Comment by rlcee** [comment]
OK, should I merge this or just approve it? Or should I merge this and the CI PR at the same time?

**Comment by ryuwd** [comment]
This can be merged. I'll keep a lookout in case anything breaks and push a fix if needed

**Comment by ryuwd** [comment]
Logs are cleaner now:

image

**Pull request merged**
