### PR TITLE
test runner; cleanup old files

### PR DESCRIPTION
**Pull request by ryuwd**
cc @rlcee 
Something I quickly wrote to illustrate the ideas I had to decouple test behaviour from codetools scripts with an easy-to-understand configuration file based approach

The test runner leverages the many features of `snakemake`. Runs the commands in parallel, and supports dependencies on other tests. 

`run_tests`: e.g. `run_tests ./Offline/`
- looks for `Offline/.tests.yml` 
    - if this is dropped into the root of Offline this should run the current suite of tests, except for rootOverlaps and g4surfacecheck
```yaml
tests:
    ceSimReco:
        fcl: Validation/ceSimReco.fcl
        events: 10
        #flags: "-S etc.txt"
    
    g4test_03MT:
        fcl: "Mu2eG4/fcl/g4test_03MT.fcl"
        events: 10
        cores: 5 # "all" to use all cores on the machine

    transportOnly:
        fcl: "Mu2eG4/fcl/transportOnly.fcl"
        events: 1
    
    POT: 
        fcl: "JobConfig/beam/POT_validation.fcl"
        events: 1
    
    g4study:
        fcl: "Mu2eG4/g4study/g4study.fcl"
        events: 1
    
    cosmicSimReco:
        fcl: "Validation/cosmicSimReco.fcl"
        events: 1


    rootOverlaps:
        script: "bin/rootOverlaps.sh" # ???

    g4SurfaceCheck:
        script: "bin/g4surfaceCheck.sh" # ???
    
    
    ceSteps:
        fcl: "Validation/ceSteps.fcl"
        events: 100
    ceDigi: 
        fcl: "Validation/ceDigi.fcl"
        events: 100
        needs: [ceSteps]
    muDauSteps: 
        fcl: "Validation/muDauSteps.fcl"
        events: 10000
        needs: [ceDigi]
    ceMix:
        fcl: "Validation/ceMix.fcl"
        events: 100
        needs: [muDauSteps]

```
- runs tests in parallel using `snakemake`
- prints a result table, outputs results in csv format at `test_results.txt`
    - can be read by bash script to create the github markdown table on the comment

### example output (will obviously fail as I am not running this on jenkins or gpvms)
```
(smk) roneil@Ryunosukes-MBP codetools % ./bin/run_tests .
Running tests in .
Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 16
Rules claiming more threads will be scaled down.
Job counts:
        count   jobs
        1       all
        10      mu2e_test_fcl
        2       mu2e_test_script
        13
Select jobs to execute...

[Thu Jun  3 17:29:29 2021]
rule mu2e_test_fcl:
    output: g4study.fcl_return_code
    jobid: 5
    wildcards: test_name=g4study


[Thu Jun  3 17:29:29 2021]
rule mu2e_test_fcl:
    output: ceSteps.fcl_return_code
    jobid: 7
    wildcards: test_name=ceSteps


[Thu Jun  3 17:29:29 2021]
rule mu2e_test_fcl:
    output: transportOnly.fcl_return_code
    jobid: 3
    wildcards: test_name=transportOnly


[Thu Jun  3 17:29:29 2021]
rule mu2e_test_script:
    output: g4SurfaceCheck.script_return_code
    jobid: 12
    wildcards: test_name=g4SurfaceCheck


[Thu Jun  3 17:29:29 2021]
rule mu2e_test_script:
    output: rootOverlaps.script_return_code
    jobid: 11
    wildcards: test_name=rootOverlaps


[Thu Jun  3 17:29:29 2021]
rule mu2e_test_fcl:
    output: POT.fcl_return_code
    jobid: 4
    wildcards: test_name=POT


[Thu Jun  3 17:29:29 2021]
rule mu2e_test_fcl:
    output: g4test_03MT.fcl_return_code
    jobid: 2
    wildcards: test_name=g4test_03MT
    threads: 5

[Thu Jun  3 17:29:29 2021]
Error in rule mu2e_test_fcl:
    jobid: 5
    output: g4study.fcl_return_code
    shell:
        
        set +o pipefail;
        set +e;
        echo "mu2e -c Mu2eG4/g4study/g4study.fcl -n 1  > g4study.log 2>&1" > g4study.log
        mu2e -c Mu2eG4/g4study/g4study.fcl -n 1  >> g4study.log  2>&1
        RC=$?
        echo "$RC" > g4study.fcl_return_code
        [[ $RC = "0" ]] && touch g4study.SUCCESS || touch g4study.FAILED
        exit $RC
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
[Thu Jun  3 17:29:29 2021]


Error in rule mu2e_test_fcl:
[Thu Jun  3 17:29:29 2021]
Job failed, going on with independent jobs.
    jobid: 7
rule mu2e_test_fcl:
    output: ceSimReco.fcl_return_code
    jobid: 1
    wildcards: test_name=ceSimReco
    output: ceSteps.fcl_return_code

    shell:
        
        set +o pipefail;
        set +e;
        echo "mu2e -c Validation/ceSteps.fcl -n 100  > ceSteps.log 2>&1" > ceSteps.log
        mu2e -c Validation/ceSteps.fcl -n 100  >> ceSteps.log  2>&1
        RC=$?
        echo "$RC" > ceSteps.fcl_return_code
        [[ $RC = "0" ]] && touch ceSteps.SUCCESS || touch ceSteps.FAILED
        exit $RC
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Job failed, going on with independent jobs.

[Thu Jun  3 17:29:29 2021]
rule mu2e_test_fcl:
    output: cosmicSimReco.fcl_return_code
    jobid: 6
    wildcards: test_name=cosmicSimReco

[Thu Jun  3 17:29:29 2021]
Error in rule mu2e_test_fcl:
    jobid: 3
    output: transportOnly.fcl_return_code
    shell:
        
        set +o pipefail;
        set +e;
        echo "mu2e -c Mu2eG4/fcl/transportOnly.fcl -n 1  > transportOnly.log 2>&1" > transportOnly.log
        mu2e -c Mu2eG4/fcl/transportOnly.fcl -n 1  >> transportOnly.log  2>&1
        RC=$?
        echo "$RC" > transportOnly.fcl_return_code
        [[ $RC = "0" ]] && touch transportOnly.SUCCESS || touch transportOnly.FAILED
        exit $RC
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Job failed, going on with independent jobs.
[Thu Jun  3 17:29:29 2021]
Error in rule mu2e_test_script:
    jobid: 12
    output: g4SurfaceCheck.script_return_code
    shell:
        
        set +o pipefail;
        set +e; 
        echo "bin/g4surfaceCheck.sh  > g4SurfaceCheck.log 2>&1" > g4SurfaceCheck.log
        bin/g4surfaceCheck.sh  >> g4SurfaceCheck.log  2>&1
        RC=$?
        echo "$RC" > g4SurfaceCheck.script_return_code
        [[ $RC = "0" ]] && touch g4SurfaceCheck.SUCCESS || touch g4SurfaceCheck.FAILED
        exit $RC
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Job failed, going on with independent jobs.
[Thu Jun  3 17:29:29 2021]
Error in rule mu2e_test_fcl:
    jobid: 4
    output: POT.fcl_return_code
    shell:
        
        set +o pipefail;
        set +e;
        echo "mu2e -c JobConfig/beam/POT_validation.fcl -n 1  > POT.log 2>&1" > POT.log
        mu2e -c JobConfig/beam/POT_validation.fcl -n 1  >> POT.log  2>&1
        RC=$?
        echo "$RC" > POT.fcl_return_code
        [[ $RC = "0" ]] && touch POT.SUCCESS || touch POT.FAILED
        exit $RC
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Job failed, going on with independent jobs.
[Thu Jun  3 17:29:30 2021]
Error in rule mu2e_test_fcl:
    jobid: 1
    output: ceSimReco.fcl_return_code
    shell:
        
        set +o pipefail;
        set +e;
        echo "mu2e -c Validation/ceSimReco.fcl -n 10  > ceSimReco.log 2>&1" > ceSimReco.log
        mu2e -c Validation/ceSimReco.fcl -n 10  >> ceSimReco.log  2>&1
        RC=$?
        echo "$RC" > ceSimReco.fcl_return_code
        [[ $RC = "0" ]] && touch ceSimReco.SUCCESS || touch ceSimReco.FAILED
        exit $RC
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Job failed, going on with independent jobs.
[Thu Jun  3 17:29:30 2021]
Error in rule mu2e_test_fcl:
    jobid: 6
    output: cosmicSimReco.fcl_return_code
    shell:
        
        set +o pipefail;
        set +e;
        echo "mu2e -c Validation/cosmicSimReco.fcl -n 1  > cosmicSimReco.log 2>&1" > cosmicSimReco.log
        mu2e -c Validation/cosmicSimReco.fcl -n 1  >> cosmicSimReco.log  2>&1
        RC=$?
        echo "$RC" > cosmicSimReco.fcl_return_code
        [[ $RC = "0" ]] && touch cosmicSimReco.SUCCESS || touch cosmicSimReco.FAILED
        exit $RC
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Job failed, going on with independent jobs.
[Thu Jun  3 17:29:30 2021]
Error in rule mu2e_test_fcl:
    jobid: 2
    output: g4test_03MT.fcl_return_code
    shell:
        
        set +o pipefail;
        set +e;
        echo "mu2e -c Mu2eG4/fcl/g4test_03MT.fcl -n 10  > g4test_03MT.log 2>&1" > g4test_03MT.log
        mu2e -c Mu2eG4/fcl/g4test_03MT.fcl -n 10  >> g4test_03MT.log  2>&1
        RC=$?
        echo "$RC" > g4test_03MT.fcl_return_code
        [[ $RC = "0" ]] && touch g4test_03MT.SUCCESS || touch g4test_03MT.FAILED
        exit $RC
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Job failed, going on with independent jobs.
[Thu Jun  3 17:29:30 2021]
Error in rule mu2e_test_script:
    jobid: 11
    output: rootOverlaps.script_return_code
    shell:
        
        set +o pipefail;
        set +e; 
        echo "bin/rootOverlaps.sh  > rootOverlaps.log 2>&1" > rootOverlaps.log
        bin/rootOverlaps.sh  >> rootOverlaps.log  2>&1
        RC=$?
        echo "$RC" > rootOverlaps.script_return_code
        [[ $RC = "0" ]] && touch rootOverlaps.SUCCESS || touch rootOverlaps.FAILED
        exit $RC
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Job failed, going on with independent jobs.
Exiting because a job execution failed. Look above for error message
Complete log: /Users/roneil/codetools/.snakemake/log/2021-06-03T172929.307523.snakemake.log
Type                Test Name                               STATUS    RC    Logfile                                                     
-------------------------------------------------------------------------------------------------
FCL                 ceSimReco                               FAIL      127   ceSimReco.log                                               
FCL                 g4test_03MT                             FAIL      127   g4test_03MT.log                                             
FCL                 transportOnly                           FAIL      127   transportOnly.log                                           
FCL                 POT                                     FAIL      127   POT.log                                                     
FCL                 g4study                                 FAIL      127   g4study.log                                                 
FCL                 cosmicSimReco                           FAIL      127   cosmicSimReco.log                                           
SCRIPT              rootOverlaps                            FAIL      127   rootOverlaps.log                                            
SCRIPT              g4SurfaceCheck                          FAIL      127   g4SurfaceCheck.log                                          
FCL                 ceSteps                                 FAIL      127   ceSteps.log                                                 
n/a                 ceDigi                                  NORUN     n/a   ceDigi.log                                                  
n/a                 muDauSteps                              NORUN     n/a   muDauSteps.log                                              
n/a                 ceMix                                   NORUN     n/a   ceMix.log        
```

### CODE REVIEW

**Comment by rlcee** [comment]
How willing are you to stay involved in the maintenance of the Mu2e github CI?  I'm happy to see you responding to the harder questions, which would take me much longer to investigate.  @kutschke do we have anyone in mind to officially learn this system and take over for Ryun?

As a dinosaur, I like vanilla systems which I can understand quickly, but I don't want to stand in the way of progress, so if you want to maintain this or if Rob will recruit someone else to maintain it, then my preference doesn't matter.  But if I am supposed to keep this going for the foreseeable future, and you will disappear at some point, then I'd rather not introduce another layer and external dependence into a system which already has several of each.  

Meanwhile, could you add to the top of run_tests.sh the requirements on PACKAGE_PATHS and its typical use, and any other things the user might want to know.  What is and where is all_tests.txt?  What goes in .tests.yaml, if anything?   Where will .test.yaml be kept? As you probably saw, I recently made mods for Muse and Production fcl.  One of the philosophies of Muse is that we don't write anything in the repo directories, so writing .tests.yaml in Offline would break this principle.  Can this be avoided, or is the proposal to commit it in that location (which would be OK by the rule)?

Also, while I have you here, do you have a method to run the current build test script locally?  As you probably saw, I was testing my changes in situ, which is a little messy.  Thanks

**Comment by ryuwd** [comment]
> How willing are you to stay involved in the maintenance of the Mu2e github CI?

I am perfectly happy to answer questions and occasionally chime in / assist / guide the new maintainer when things go wrong - I expect I could help out with that for quite a while, as most of the code and conversations on GitHub are easy to get involved in and stay up to date with.

However, I find myself with increasingly less time recently, as things ramp up on the LHCb side. It will become more difficult for me to select time to lead any work on investigating problems, and to come up with hotfixes as things break. 
I will also not be able to actively investigate any issues at all once I lose access to Jenkins, as my FNAL computing account will expire in a few short months.

> As a dinosaur, I like vanilla systems which I can understand quickly, but I don't want to stand in the way of progress, so if you want to maintain this or if Rob will recruit someone else to maintain it, then my preference doesn't matter. But if I am supposed to keep this going for the foreseeable future, and you will disappear at some point, then I'd rather not introduce another layer and external dependence into a system which already has several of each.

Fair enough - I chose [`snakemake`](https://snakemake.readthedocs.io/en/stable/) to avoid boilerplate and get the job done quickly, and because it's a tool I use regularly in one of my analyses. I realise now that introducing a nonstandard dependency might not have been the best idea.

Of course, the `.smk` file and use of `snakemake` can be replaced with the existing bash code I wrote in `build.sh` in the `do_runstep` routine. And a more bash-friendly approach to configuring the tests (i.e. not YAML) can be used. Perhaps pure-python would be a more ideal alternative to bash.

> Meanwhile, could you add to the top of run_tests.sh the requirements on PACKAGE_PATHS and its typical use, and any other things the user might want to know. What is and where is all_tests.txt? What goes in .tests.yaml, if anything? Where will .test.yaml be kept? 

Will do - I'll also add the explanations below:

- `PACKAGE PATH` is just the relative path to the directory to be tested - specifically the directory holding a `.tests.yml`.
- `all_tests.txt` is a space-separated list of tests dumped by the `snakemake` configuration (`.smk`) file, where the `.tests.yml` file is processed and the DAG is generated (i.e. what tests to run, what commands to run, what arguments are needed, what are the input and output files)
- `.tests.yml` is a YAML configuration file that lists all the tests and parameters to run the tests with, whether they need other tests to have run first (`needs:`), and how many `cores:` are needed (default 1). It supports a `fcl:` key or a `script:` key (mutually exclusive parameters).
- `.tests.yml` is supposed to be committed to the repository to be tested.

> As you probably saw, I recently made mods for Muse and Production fcl. One of the philosophies of Muse is that we don't write anything in the repo directories, so writing .tests.yaml in Offline would break this principle. Can this be avoided, or is the proposal to commit it in that location (which would be OK by the rule)?

I see, in this case, since the `all_tests.txt` and log files are written inside the repo, this rule is violated. I suppose a simple workaround is to create a temporary directory separate of the source directory, or to just dump these files in the CWD.

Perhaps an even better solution to what I've proposed here is to implement a testing workflow within muse itself e.g. `muse test <Package Name>`.

> Also, while I have you here, do you have a method to run the current build test script locally? As you probably saw, I was testing my changes in situ, which is a little messy. Thanks

These scripts are designed to run inside jenkins, but I imagine you could get them to run locally by setting up an empty workspace folder and run this
```
mkdir workspace && cd workspace
git clone git@github.com:mu2e/Offline
git clone git@github.com:mu2e/codetools
git clone git@github.com:mu2e/CI

GITHUB_TOKEN="personal access token generated on github" # https://github.com/settings/tokens
REPOSITORY="Mu2e/Offline"
PULL_REQUEST="PR number" 
COMMIT_SHA="PR commit sha hash"  # this commit is checked out and merged into MASTER_COMMIT_SHA
MASTER_COMMIT_SHA="HEAD"

source codetools/bin/gh_pr_bootstrap.sh mu2e-offline-build-test
```

keep in mind this will post results to that PR and change labels, etc... but nothing destructive or weird should happen

**Comment by rlcee** [comment]
> my FNAL computing account will expire

I believe we can renew that indefinitely

> implement a testing workflow within muse itself e.g. muse test <Package Name>.

I do have a target
 muse build VAL0
which will run ceSimReco.  That is about to break because we 
are pulling most fcl out of Offline, including ceSimReco.fcl
Now, pretty much all tests need to run with Offline and Production repos together,
which breaks the concept of a repo containing its own tests.
Another way to go is in Production or a new repo called OfflineTests, we put
whatever we want for test sequences.  It is probably a good idea to make
more lengthy sequences available to users in a script so they can run the tests
before a complex commit.  Maybe we could call that new repo codetools (LOL - I went full circle).  

How to merge testing in github CI with other goals such as 
build tests, nightly tests, geant tests, and user needs, deserves some thought and discussion.
Right now it is scattered, but could be brought together.

I'm about to leave on a week vacation, and I know Rob is thinking about how to maintain
github CI without you - maybe we can continue this later.

**Comment by ryuwd** [comment]
> Another way to go is in Production or a new repo called OfflineTests, we put
whatever we want for test sequences. It is probably a good idea to make
more lengthy sequences available to users in a script so they can run the tests
before a complex commit

> I do have a target `muse build VAL0` which will run ceSimReco.

How about then a new muse repository (`OfflineTests` as you suggest), which contains `scons` targets (rather than shell scripts) that run different configurations of tests?

```
muse build ceSimReco # runs ceSimReco only

muse build rootOverlaps # runs overlap check only

muse build test # runs all CI test targets, which might trigger the ceSimReco, and rootOverlaps targets, for example

muse build nightly-validation # runs all nightly validation tests (???) 
```
scons seems like a nice way to do this because it is already well understood and the `-j N` flag can be used to run tests in parallel, which would be useful on jenkins, or anywhere really. 
If I understand properly how muse works, either the user links the `OfflineTests` repo or it is linked automatically and lives somewhere on cvmfs so they would just have to call `muse build <test target name>` to run the test target(s).

In contrast, this approach works nicely in KinKal, which has a `make test` target that just runs all unit test executables. It works on both the user side and in the CI quite well e.g. https://github.com/KFTrack/KinKal/runs/2503492874#step:10:1

> How to merge testing in github CI with other goals such as
build tests, nightly tests, geant tests, and user needs, deserves some thought and discussion.
Right now it is scattered, but could be brought together.

+1

I don't know how long my `do_runstep` code will hold up to task especially with lots of things changing since I wrote them. Moving the test workflows out of these jenkins shell scripts will keep them a lot simpler, too. 

> I'm about to leave on a week vacation, and I know Rob is thinking about how to maintain
github CI without you - maybe we can continue this later.

OK. Have a good vacation!

**Pull request closed without merging**
